### ISSUE TITLE
Origin x.x.x.x is not allowed by Access-Control-Allow-Origin. after adding this gem

### ISSUE THREAD

**Issue by amrnt** [kyledrake/sinatra-synchrony#7]
`XMLHttpRequest cannot load http://0.0.0.0:3001/X.json. Origin http://0.0.0.0:3000 is not allowed by Access-Control-Allow-Origin.`

and i have in my `config.ru` this already and it was working before I added `sinatra-synchrony`!

``` ruby
use Rack::ResponseHeaders do |headers|
  headers['Access-Control-Allow-Origin'] = '*'
  headers['Access-Control-Request-Method'] = '*'
end
```

**Comment by kyledrake** [comment]
Try adding this inside your Sinatra app, like so:

register Sinatra::Synchrony
use Rack::ResponseHeaders do ...

I think the root of this problem is that it's being loaded before Rack::FiberPool. You want to put Rack::FiberPool before everything in the application. You can move Rack::FiberPool to config.ru of course too, the sinatra-synchrony source is dead simple and you can deconstruct it immediately.

Let me know if this works! I'm not sure what else it could be.

**Comment by amrnt** [comment]
I;m not getting you.

`use Rack::ResponseHeaders do ...` is for cross app config so its in `config.ru`

`register Sinatra::Synchrony` in `config.ru` wont work!

sorry, but what to do exactly?

**Comment by kyledrake** [comment]
Sinatra-synchrony is just a convenience helper. You can roll all of it directly into config.ru very easily. Instead of using sinatra-synchrony, put use Rack::FiberPool into your config.ru directly: https://github.com/kyledrake/sinatra-synchrony/blob/master/lib/sinatra/synchrony.rb#L12

**Comment by amrnt** [comment]
This where we fail! We dont read the code!! Works as expected thanks!

**Comment by kyledrake** [comment]
Glad it worked! Best of luck :)
